package cliente;

import P2P.cc;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author brunis46
 */
public class Chat extends javax.swing.JFrame {

    private cc amigo;
    private String correo;

    public Chat(cc friend, String mail, String mail2) {
        amigo = friend;
        correo = mail;
        initComponents();
        this.getNombre().setText("Conversación de " + mail + " con " + mail2);
    }

    public Chat() {
        initComponents();

    }

    public JTextField getMensajeAMandar() {
        return mensajeAMandar;
    }

    public void setMensajeAMandar(JTextField mensajeAMandar) {
        this.mensajeAMandar = mensajeAMandar;
    }

    public cc getAmigo() {
        return amigo;
    }

    public void setAmigo(cc amigo) {
        this.amigo = amigo;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public JButton getEnviar() {
        return enviar;
    }

    public void setEnviar(JButton enviar) {
        this.enviar = enviar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getMensajes() {
        return mensajes;
    }

    public void setMensajes(JTextArea mensajes) {
        this.mensajes = mensajes;
    }

    public JLabel getNombre() {
        return nombre;
    }

    public void setNombre(JLabel nombre) {
        this.nombre = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensajeAMandar = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajes = new javax.swing.JTextArea();
        nombre = new javax.swing.JLabel();
        enviarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mensajeAMandar.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        mensajeAMandar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mensajeAMandarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mensajeAMandarFocusLost(evt);
            }
        });

        enviar.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        mensajes.setEditable(false);
        mensajes.setColumns(20);
        mensajes.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        mensajes.setRows(5);
        jScrollPane1.setViewportView(mensajes);

        nombre.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        nombre.setText("jLabel1");

        enviarArchivo.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        enviarArchivo.setText("Enviar archivo");
        enviarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensajeAMandar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enviarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensajeAMandar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        amigo.talk(this.correo, this.getMensajeAMandar().getText());

        Calendar calendario = new GregorianCalendar();
        this.getMensajes().setText(this.getMensajes().getText() + "\n\n" + this.getCorreo() + "("
                + calendario.get(Calendar.HOUR_OF_DAY)
                + ":" + calendario.get(Calendar.MINUTE)
                + "):      " + this.getMensajeAMandar().getText());
        this.getMensajes().setCaretPosition(this.getMensajes().getDocument().getLength());
    }//GEN-LAST:event_enviarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void mensajeAMandarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mensajeAMandarFocusGained
        // TODO add your handling code here:
        this.getMensajeAMandar().setText("");
    }//GEN-LAST:event_mensajeAMandarFocusGained

    private void mensajeAMandarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mensajeAMandarFocusLost

    }//GEN-LAST:event_mensajeAMandarFocusLost

    private void enviarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.showOpenDialog(this);
        byte[] archivoEnviar = fileToBytes(fileChooser.getSelectedFile());
        amigo.enviarArchivo(correo, fileChooser.getName(fileChooser.getSelectedFile()) ,archivoEnviar);

        Calendar calendario = new GregorianCalendar();
        this.getMensajes().setText(this.getMensajes().getText() + "\n\n" + this.getCorreo() + "("
                + calendario.get(Calendar.HOUR_OF_DAY)
                + ":" + calendario.get(Calendar.MINUTE)
                + ")  ha enviado un archivo");
        this.getMensajes().setCaretPosition(this.getMensajes().getDocument().getLength());
    }//GEN-LAST:event_enviarArchivoActionPerformed

    private byte[] fileToBytes(File file) {
        try {
            byte buffer[] = new byte[(int) file.length()];
            BufferedInputStream input = new BufferedInputStream(new FileInputStream(file.getAbsoluteFile()));
            input.read(buffer, 0, buffer.length);
            input.close();
            return (buffer);
        } catch (Exception e) {
            System.out.println("FileImpl: " + e.getMessage());
            e.printStackTrace();
            return (null);
        }
    }

    public void createFile(String fileName, byte[] byteArray, String correo) {
        FileOutputStream fileOuputStream = null;
        String route = null;
        try {
            if (!new File(FileSystemView.getFileSystemView().getDefaultDirectory().getPath() + "/CORBA/").mkdir()) {
                System.out.println("peta al hacer el mkdir");
            }
            if (!new File(FileSystemView.getFileSystemView().getDefaultDirectory().getPath() + "/CORBA/" + correo).mkdir()) {
                System.out.println("peta al hacer el mkdir");
            }
            route = FileSystemView.getFileSystemView().getDefaultDirectory().getPath() + "/CORBA/" + correo + "/" + fileName;
            fileOuputStream = new FileOutputStream(route);
            fileOuputStream.write(byteArray);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (route != null) {
                    System.out.println("File received is in: " + route);
                }
                fileOuputStream.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JButton enviarArchivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mensajeAMandar;
    private javax.swing.JTextArea mensajes;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
