package cliente;

import P2P.amigo;
import P2P.cc;
import P2P.ccHelper;
import P2P.ccServant;
import P2P.cs;
import P2P.sc;
import P2P.scServant;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NameComponent;
import org.omg.CosNaming.NamingContext;
import org.omg.CosNaming.NamingContextHelper;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;
import org.omg.PortableServer.POAManagerPackage.AdapterInactive;
import org.omg.PortableServer.POAPackage.ServantNotActive;
import org.omg.PortableServer.POAPackage.WrongPolicy;

/**
 *
 * @author brunis46
 */
public class PanelLogueo extends javax.swing.JFrame {

    private cs server;
    private sc servidorCliente;
    private cc cliente;
    private org.omg.CORBA.ORB orb;

    /**
     * Creates new form PanelLogueo
     */
    public PanelLogueo(cs aux, org.omg.CORBA.ORB orb2) {
        initComponents();
        server = aux;
        orb = orb2;
    }

    public PanelLogueo() {
        initComponents();
    }

    public cs getServer() {
        return server;
    }

    public void setServer(cs server) {
        this.server = server;
    }

    public sc getServidorCliente() {
        return servidorCliente;
    }

    public void setServidorCliente(sc servidorCliente) {
        this.servidorCliente = servidorCliente;
    }

    public cc getCliente() {
        return cliente;
    }

    public void setCliente(cc cliente) {
        this.cliente = cliente;
    }

    public JButton getAcceder() {
        return acceder;
    }

    public void setAcceder(JButton acceder) {
        this.acceder = acceder;
    }

    public JPasswordField getContrasena() {
        return contrasena;
    }

    public void setContrasena(JPasswordField contrasena) {
        this.contrasena = contrasena;
    }

    public JPasswordField getContrasena1() {
        return contrasena1;
    }

    public void setContrasena1(JPasswordField contrasena1) {
        this.contrasena1 = contrasena1;
    }

    public JTextField getCorreo() {
        return correo;
    }

    public void setCorreo(JTextField correo) {
        this.correo = correo;
    }

    public JTextField getCorreo1() {
        return correo1;
    }

    public void setCorreo1(JTextField correo1) {
        this.correo1 = correo1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public JButton getRegistro() {
        return registro;
    }

    public void setRegistro(JButton registro) {
        this.registro = registro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        correo = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();
        acceder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        correo1 = new javax.swing.JTextField();
        contrasena1 = new javax.swing.JPasswordField();
        registro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 251, 244));

        correo.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        correo.setText("usuario@example.com");

        contrasena.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N

        acceder.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        acceder.setText("Acceder");
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel1.setText("Correo electrónico:");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        jLabel3.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(159, 159, 159))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(acceder)
                                    .addGap(209, 209, 209)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(acceder)
                .addGap(78, 78, 78))
        );

        jTabbedPane1.addTab("Login", jPanel1);

        jPanel2.setBackground(new java.awt.Color(236, 251, 244));

        correo1.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        correo1.setText("usuario@example.com");
        correo1.setToolTipText("");

        contrasena1.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N

        registro.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        registro.setText("Registrarse");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel4.setText("Correo electrónico:");

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel5.setText("Contraseña:");

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        jLabel6.setText("Registro");

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel7.setText("Nombre:");

        nombre.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(correo1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(contrasena1)
                            .addComponent(nombre))
                        .addGap(144, 144, 144))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(registro)
                .addGap(183, 183, 183))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(registro)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private cc actualizarServicioNombresCC(String correo, Principal paux) {
        cc yoMismo = null;

        try {
            POA rootPOA;
            org.omg.CORBA.Object o = orb.resolve_initial_references("RootPOA");
            rootPOA = POAHelper.narrow(o);
            rootPOA.the_POAManager().activate();

            HashMap<String, Chat> amig = new HashMap<>();

            ccServant c = new ccServant(orb, correo, paux);
            o = rootPOA.servant_to_reference(c);

            String ruta1 = correo + "cc";

            NamingContext nc = NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));
            NameComponent[] nco = {new NameComponent(ruta1, "")};
            nc.rebind(nco, o);

            org.omg.CORBA.Object obj = nc.resolve(nco);
            yoMismo = ccHelper.narrow(obj);

        } catch (InvalidName | ServantNotActive | WrongPolicy | NotFound | CannotProceed | org.omg.CosNaming.NamingContextPackage.InvalidName | AdapterInactive ex) {
            Logger.getLogger(PanelLogueo.class.getName()).log(Level.SEVERE, null, ex);
        }

        return yoMismo;
    }

    private void actualizarServicioNombresSC(String correo, Principal pr) {

        try {
            POA rootPOA;
            org.omg.CORBA.Object o = orb.resolve_initial_references("RootPOA");
            rootPOA = POAHelper.narrow(o);
            rootPOA.the_POAManager().activate();

            NamingContext nc = NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));
            String ruta = correo + "sc";
            NameComponent[] nco = {new NameComponent(ruta, "")};

            scServant s = new scServant(pr);
            o = rootPOA.servant_to_reference(s);

            nc.rebind(nco, o);

        } catch (InvalidName | ServantNotActive | WrongPolicy | NotFound | CannotProceed | org.omg.CosNaming.NamingContextPackage.InvalidName | AdapterInactive ex) {
            Logger.getLogger(PanelLogueo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed

        Pattern p = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher m = p.matcher(correo1.getText());

        String contrasenaEnvio = new String(this.getContrasena().getPassword());

        if (contrasenaEnvio.length() < 8 || contrasenaEnvio.length() > 20) {
            JOptionPane.showMessageDialog(this,
                    "La contrase?a introducida debe poseer entre 6 y 20 caracteres");
        } else {
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this,
                        "El correo introducido no posee el formato adecuado");
            } else {
                amigo[] amigos;
                amigos = server.logueo(this.getCorreo().getText(), contrasenaEnvio);
                if (amigos[0].correo.equals("fallo@fallo.com")) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario o contrase?a introducidos no son validos");
                } else if (amigos[0].correo.equals("relogueo@relogueo.com")) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario ya ha iniciado sesi?n");
                } else {
                    Principal pr = new Principal(server, this.getCorreo().getText(), orb, amigos);
                    pr.setYo(actualizarServicioNombresCC(this.getCorreo().getText(), pr));
                    actualizarServicioNombresSC(this.getCorreo().getText(), pr);
                    pr.setVisible(true);
                    this.setVisible(false);
                    pr.recibirPeticionesAmistad();
                    this.dispose();
                }
            }
        }


    }//GEN-LAST:event_accederActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed

        Pattern p = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher m = p.matcher(correo1.getText());

        String contrasenaEnvio = new String(this.getContrasena1().getPassword());

        if (contrasenaEnvio.length() < 8 || contrasenaEnvio.length() > 20) {
            JOptionPane.showMessageDialog(this,
                    "La contrase?a introducida debe poseer entre 8 y 20 caracteres");
        } else {
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this,
                        "El correo introducido no posee el formato adecuado");
            } else {
                if (this.nombre.getText().length() < 2) {
                    JOptionPane.showMessageDialog(this,
                            "El nombre introducido no posee el formato adecuado");
                } else {
                    short tmp = server.registro(this.getCorreo1().getText(), contrasenaEnvio, this.getNombre().getText());
                    if (tmp == 0) {
                        Principal pr = new Principal(server, this.getCorreo1().getText(), orb, null);
                        pr.setYo(actualizarServicioNombresCC(this.getCorreo().getText(), pr));
                        actualizarServicioNombresSC(this.getCorreo1().getText(), pr);
                        pr.setVisible(true);
                        this.setVisible(false);
                        this.dispose();
                    } else if (tmp == 1) {
                            JOptionPane.showMessageDialog(this,
                                "Ya existe un usuario registrado con ese correo");
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Fallo con el registro");
                    }
                }
            }
        }

    }//GEN-LAST:event_registroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        orb.destroy();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelLogueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceder;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPasswordField contrasena1;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton registro;
    // End of variables declaration//GEN-END:variables
}
