package P2P;


/**
* P2P/bytesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 17 de abril de 2016 04H16' CEST
*/

public final class bytesHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public bytesHolder ()
  {
  }

  public bytesHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P2P.bytesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    P2P.bytesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P2P.bytesHelper.type ();
  }

}
