package P2P;


/**
* P2P/cc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 16 de abril de 2016 18H31' CEST
*/

public interface cc extends ccOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cc
