package P2P;


/**
* P2P/cc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 14 de abril de 2016 18H52' CEST
*/

public interface cc extends ccOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

    public void inicializar(cc cliente2, String mail);
} // interface cc
