package P2P;


/**
* P2P/ccOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 17 de abril de 2016 18H33' CEST
*/

public interface ccOperations 
{
  void talk (String correo, String mensaje);
  void init (String correo);
  void enviarArchivo (String correo1, String nombreArchivo, byte[] archivo);
} // interface ccOperations
