package P2P;


/**
* P2P/ccOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 15 de abril de 2016 17H04' CEST
*/

public interface ccOperations 
{
  void talk (String mensaje);
  void init (String correo);
} // interface ccOperations
