package P2P;


/**
* P2P/ccPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 17 de abril de 2016 03H04' CEST
*/

public abstract class ccPOA extends org.omg.PortableServer.Servant
 implements P2P.ccOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("talk", new java.lang.Integer (0));
    _methods.put ("init", new java.lang.Integer (1));
    _methods.put ("enviarArchivo", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // P2P/cc/talk
       {
         String correo = in.read_string ();
         String mensaje = in.read_string ();
         this.talk (correo, mensaje);
         out = $rh.createReply();
         break;
       }

       case 1:  // P2P/cc/init
       {
         String correo = in.read_string ();
         this.init (correo);
         out = $rh.createReply();
         break;
       }

       case 2:  // P2P/cc/enviarArchivo
       {
         String correo1 = in.read_string ();
         byte archivo[] = P2P.bytesHelper.read (in);
         this.enviarArchivo (correo1, archivo);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:P2P/cc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public cc _this() 
  {
    return ccHelper.narrow(
    super._this_object());
  }

  public cc _this(org.omg.CORBA.ORB orb) 
  {
    return ccHelper.narrow(
    super._this_object(orb));
  }


} // class ccPOA
