package P2P;


/**
* P2P/cs.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 21H33' CEST
*/

public interface cs extends csOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cs
