package P2P;


/**
* P2P/scOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 16 de abril de 2016 22H05' CEST
*/

public interface scOperations 
{
  void sendAmistad (String correo);
  void notificar (String correo, boolean estado);
} // interface scOperations
