// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "interface.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



test::test2_ptr test::test2_Helper::_nil() {
  return ::test::test2::_nil();
}

::CORBA::Boolean test::test2_Helper::is_nil(::test::test2_ptr p) {
  return ::CORBA::is_nil(p);

}

void test::test2_Helper::release(::test::test2_ptr p) {
  ::CORBA::release(p);
}

void test::test2_Helper::marshalObjRef(::test::test2_ptr obj, cdrStream& s) {
  ::test::test2::_marshalObjRef(obj, s);
}

test::test2_ptr test::test2_Helper::unmarshalObjRef(cdrStream& s) {
  return ::test::test2::_unmarshalObjRef(s);
}

void test::test2_Helper::duplicate(::test::test2_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

test::test2_ptr
test::test2::_duplicate(::test::test2_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

test::test2_ptr
test::test2::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


test::test2_ptr
test::test2::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

test::test2_ptr
test::test2::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_test2 _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_test2* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_test2;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* test::test2::_PD_repoId = "IDL:test/test2:1.0";


test::_objref_test2::~_objref_test2() {
  
}


test::_objref_test2::_objref_test2(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::test::test2::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
test::_objref_test2::_ptrToObjRef(const char* id)
{
  if (id == ::test::test2::_PD_repoId)
    return (::test::test2_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::test::test2::_PD_repoId))
    return (::test::test2_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for test::test2::say_hello

// Proxy call descriptor class. Mangled signature:
//  void
class _0RL_cd_035b7071183ffbcf_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_035b7071183ffbcf_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
    
  
  static const char* const _user_exns[];

  
};

const char* const _0RL_cd_035b7071183ffbcf_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_035b7071183ffbcf_10000000(omniCallDescriptor*, omniServant* svnt)
{
  
  test::_impl_test2* impl = (test::_impl_test2*) svnt->_ptrToInterface(test::test2::_PD_repoId);
  impl->say_hello();


}

void test::_objref_test2::say_hello()
{
  _0RL_cd_035b7071183ffbcf_00000000 _call_desc(_0RL_lcfn_035b7071183ffbcf_10000000, "say_hello", 10);


  _invoke(_call_desc);



}

test::_pof_test2::~_pof_test2() {}


omniObjRef*
test::_pof_test2::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::test::_objref_test2(ior, id);
}


::CORBA::Boolean
test::_pof_test2::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::test::test2::_PD_repoId))
    return 1;
  
  return 0;
}

const test::_pof_test2 _the_pof_test_mtest2;

test::_impl_test2::~_impl_test2() {}


::CORBA::Boolean
test::_impl_test2::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "say_hello")) {

    _0RL_cd_035b7071183ffbcf_00000000 _call_desc(_0RL_lcfn_035b7071183ffbcf_10000000, "say_hello", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
test::_impl_test2::_ptrToInterface(const char* id)
{
  if (id == ::test::test2::_PD_repoId)
    return (::test::_impl_test2*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::test::test2::_PD_repoId))
    return (::test::_impl_test2*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
test::_impl_test2::_mostDerivedRepoId()
{
  return ::test::test2::_PD_repoId;
}

POA_test::test2::~test2() {}

