package test;


/**
* test/test2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 12 de abril de 2016 21H39' CEST
*/

public interface test2 extends test2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface test2
