package test;


/**
* test/test2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 12 de abril de 2016 21H39' CEST
*/

public interface test2Operations 
{
  void say_hello ();
} // interface test2Operations
