package test;

/**
* test/test2Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 12 de abril de 2016 21H39' CEST
*/

public final class test2Holder implements org.omg.CORBA.portable.Streamable
{
  public test.test2 value = null;

  public test2Holder ()
  {
  }

  public test2Holder (test.test2 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = test.test2Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    test.test2Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return test.test2Helper.type ();
  }

}
