#ifndef __ECHO_CALLBACK_IDL__
#define __ECHO_CALLBACK_IDL__

module P2P{
	interface cc{
		void talk(in string mensaje);
		void init(in string correo);
	};
	struct amigo{
		string correo;
		boolean estado;
	};
	typedef sequence<amigo> amigos;
	typedef sequence<string> buscar;
	interface sc{
		void sendAmistad(in string correo);
		void notificar(in string correo, in boolean estado);
	};
	interface cs{
		void pedirAmistad(in string correo1, in string correo2);
		amigos logueo(in string correo, in string pass);
		boolean registro(in string correo, in string pass, in string nombre);
		boolean desregistro(in string correo);
		boolean modPass(in string correo, in string pass1, in string pass2);
		boolean deslogueo(in string correo);
		boolean aceptarAmistad(in string correo1, in string correo2);
		buscar buscaAmigos(in string nombre);
	};
};

#endif