package P2P;


/**
* P2P/cc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 15 de abril de 2016 17H04' CEST
*/

public interface cc extends ccOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cc
