package P2P;


/**
* P2P/ccOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 21H33' CEST
*/

public interface ccOperations 
{
  void talk (String mensaje);
} // interface ccOperations
