package P2P;


/**
* P2P/ccOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 16 de abril de 2016 22H05' CEST
*/

public interface ccOperations 
{
  void talk (String correo, String mensaje);
  void init (String correo);
} // interface ccOperations
