package P2P;


/**
* P2P/csOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 20H56' CEST
*/

public interface csOperations 
{
  void pedirAmistad (String correo1, String correo2);
  P2P.amigo[] logueo (String correo, String pass, P2P.sc tmp, P2P.cc aux);
  boolean registro (String correo, String pass, String nombre);
  boolean desregistro (String correo);
  boolean modPass (String correo, String pass1, String pass2);
  boolean deslogueo (String correo, P2P.sc aux);
  boolean aceptarAmistad (String correo1, String correo2);
  String[] buscaAmigos (String nombre);
} // interface csOperations
