package P2P;


/**
* P2P/sc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 16 de abril de 2016 22H05' CEST
*/

public interface sc extends scOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface sc
